"""Application-internal, bounded search skills for A-003 fact checking."""

from .contracts import (
    EvidenceKind,
    EvidenceRecord,
    SearchErrorCode,
    SearchResult,
    SearchStatus,
    TextbookDatabaseSearchSkill,
    TextbookSearchTool,
    UnifiedRetrievalTool,
    VectorTextbookSearchTool,
    TextbookSearchRequest,
    WebResourceSearchSkill,
    WebSearchCandidate,
    WebSearchProvider,
    WebSearchRequest,
)
from .skills import (
    DeterministicMockWebResourceSearchSkill,
    DeterministicMockWebSearchProvider,
    DisabledVectorTextbookSearchTool,
    DisabledWebResourceSearchSkill,
    ProviderBackedWebResourceSearchSkill,
    TavilyWebSearchProvider,
    web_search_skill_from_env,
    SQLiteFts5TextbookDatabaseSearchSkill,
    normalize_allowed_domain,
    normalize_allowed_domains,
    normalize_https_url,
)

__all__ = [
    "DeterministicMockWebResourceSearchSkill",
    "DeterministicMockWebSearchProvider",
    "DisabledWebResourceSearchSkill",
    "DisabledVectorTextbookSearchTool",
    "EvidenceKind",
    "EvidenceRecord",
    "ProviderBackedWebResourceSearchSkill",
    "TavilyWebSearchProvider",
    "web_search_skill_from_env",
    "SQLiteFts5TextbookDatabaseSearchSkill",
    "SearchErrorCode",
    "SearchResult",
    "SearchStatus",
    "TextbookDatabaseSearchSkill",
    "TextbookSearchTool",
    "UnifiedRetrievalTool",
    "VectorTextbookSearchTool",
    "TextbookSearchRequest",
    "WebResourceSearchSkill",
    "WebSearchCandidate",
    "WebSearchProvider",
    "WebSearchRequest",
    "normalize_allowed_domain",
    "normalize_allowed_domains",
    "normalize_https_url",
]
